FROM centos:8
RUN dnf update -y && dnf install -y python3-pip && \
    dnf clean all && rm -rf /var/cache/yum
RUN curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.10.1/minikube-linux-amd64 \
  && chmod +x minikube && mkdir -p /usr/local/bin/ && install minikube /usr/local/bin/
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
COPY dist/assisted-installer-deployment-*.tar.gz ./
RUN pip3 install ./assisted-installer-deployment-*.tar.gz
